swagger: '2.0'
info:
  description: >-
    Find high resolution royalty-free images, editorial stock photos, vector art, video footage clips and stock music licensing at the richest image search photo library online.
  version: 2.0.0
  title: TUI Media Pool
  contact:
    name: Chintan Shah
    email: chintan.shah@sptr.co
host: mediapool.io
basePath: /v2
tags:
  - name: User
    description: Users Management
  - name: Board
    description: Board Management
schemes:
  - http
  - https
paths:
# User API
  /user/save:
    post:
      tags:
      - "User"
      summary: "Redirection from ADFS"
      description: ""
      parameters:
      - in: "body"
        name: "searchObject"
        description: "Signup"
        schema:
          type: object
          properties:
            adfsId: 
              type: string
              example: 507f1f77bcf86cd799439011
            oneSignalId: 
              type: string
              example: 507f1f77bcf86cd799439011
            name:
              type: string
              example: Chintan Shah
            email:
              type: string
              example: chintan@wohlig.com
            profilePic:
              type: string
              example: http://mediapool.io:4400/images/tui.png
      responses:
        200:
          description: "Saved Sucessfully and Get AccessToken"
          example: 
              name: Chintan Shah
              email: chintan@wohlig.com
              boardCount: 2
              accessToken: 829739238729
          schema: 
            type: object
        405:
          description: "Invalid Input"
          schema:
            type: object
          example: 
              error: "Invalid Input"
  /user/logout:
    post:
      tags:
      - "User"
      summary: "Logout"
      description: "Logout User and Remove the user accessToken"
      parameters:
      - in: "header"
        description: User Access Token
        name: "accessToken"
        type: string
        example: 829739238729
      responses:
        200:
          description: "Logout Successfully"
          schema: 
            type: object
          example: 
              data: Logout Successful
        405:
          description: "Invalid Input"
          schema: 
            type: object
          example: 
              error: "Invalid Input"
  /user/search:
    post:
      tags:
      - "User"
      summary: "Search Users"
      description: "Get users with name Search with Pagination"
      parameters:
      - in: "header"
        description: User Access Token
        name: "accessToken"
        type: string
      - in: "body"
        name: "searchObject"
        example: 
          name: Chi
          pageNumber: 2
        schema:
          type: object
          properties:
            name: 
              type: string
            pageNumber: 
              type: number
      responses:
        200:
          description: "Return of User in Pagination"
          schema: 
            type: object
            example:
              options:
                start: 0
                count: 5
              total: 1209
              results:
                - _id: 507f1f77bcf86cd799439011
                  name: Chintan Shah
                - _id: 507f1f77bcf86cd799439011
                  name: Chirag Shah
                - _id: 507f1f77bcf86cd799439011
                  name: Chiraag Shah
                - _id: 507f1f77bcf86cd799439011
                  name: Chinntan Shah
                - _id: 507f1f77bcf86cd799439011
                  name: Jagruti Chintan
            properties: 
                option: 
                    type: object
                    properties: 
                        start:
                            type: number
                        count: 
                            type: number
                total:
                    type: number
                results: 
                    type: array
                    items:
                        object: number
        300:
          description: "No Data Found"
          schema: 
            type: object
          example: 
              data: "No Data Found"
        405:
          description: "Invalid Input"
          schema: 
            type: object
          example: 
              error: "Invalid Input"   
  /user/getProfile:
    post:
      tags:
      - "User"
      summary: "Get User Details"
      description: ""
      parameters:
      - in: "header"
        description: User Access Token
        name: "accessToken"
        type: string
      responses:
        200:
          description: "Return of User Detail"
          schema: 
            type: object
          example:
            name: Chintan Shah
            email: chintan@wohlig.com
            boardCount: 2
            profilePic: http://mediapool.io:4400/images/tui.png
        405:
          description: "Invalid Input"
          schema:
            type: object
          example: 
              error: "Invalid Input"
  
# Media API
  /media/search:
    post:
      tags:
      - "Media"
      summary: "Media Search"
      description: ""
      parameters:
      - in: "body"
        name: "searchObject"
        description: "Text to be searched"
        schema:
          type: object
          properties:
            name: 
              type: string
            filters: 
              type: string
            pageNumber:
              type: string
      responses:
        200:
          description: "Return of Media Objects in Pagination"
        300:
          description: "No data Found"
        405:
          description: "Invalid input"  
  
  /media/getDetail:
    post:
      tags:
      - "Media"
      summary: "Get All Media with Detail"
      description: ""
      parameters:
      - in: "body"
        name: "getObject"
        description: "Get All Media with Detail"
        schema:
          type: object
          properties:
            media_Id: 
              type: string
      responses:
        200:
          description: "Return of Media Detail with related Media"
        405:
          description: "Invalid input"  
          
  /media/downloadMedia:
    post:
      tags:
      - "Media"
      summary: "Get All Download Media"
      description: ""
      parameters:
      - in: "body"
        name: "rateMedia"
        description: "Get All Download media"
        schema:
          type: object
          properties:
            media_Id: 
              type: string
            resolution:
              type: string
      responses:
        200:
          description: "All Images with Resolutions"
        300:
          description: "No data Found"
        405:
          description: "Invalid input"  
  
# Board API
  /board/search:
    post:
      tags:
      - "Board"
      summary: "Get All Boards with Search"
      description: ""
      parameters:
      - in: "body"
        name: "searchObject"
        description: "Text to be searched"
        schema:
          type: object
          properties:
            name: 
              type: string
            pageNumber: 
              type: number
      responses:
        200:
          description: "Return of Board Objects in Pagination"
        300:
          description: "No data Found"
        405:
          description: "Invalid input"
          
  /board/getAll:
    post:
      tags:
      - "Board"
      summary: "Get all Board "
      description: ""
      parameters:
      - in: "body"
        name: "getAllObject"
        description: "Get Boards of the user"
        schema:
          type: object
          properties:
            adfsId:
              type: string
            pageNumber: 
              type: number
      responses:
        200:
          description: "Return of Boards Objects in Pagination"
        300:
          description: "No data Found"
        405:
          description: "Invalid input"
          
  /board/getOne:
    post:
      tags:
      - "Board"
      summary: "Get Board"
      description: ""
      parameters:
      - in: "body"
        name: "getObject"
        description: "Get Board of the user"
        schema:
          type: object
          properties:
            board_Id:
              type: string
            pageNumber: 
              type: number
      responses:
        200:
          description: "Return of Board Objects in Pagination"
        300:
          description: "No data Found"
        405:
          description: "Invalid input"
          
  /board/addMedia:
    post:
      tags:
      - "Board"
      summary: "Add Media to Board"
      description: ""
      parameters:
      - in: "body"
        name: "addMedia"
        description: "Add Media to the Board"
        schema:
          type: object
          properties:
            boolean: 
              type: boolean
      responses:
        200:
          description: "Successfully Added to the Board"
        405:
          description: "Error while Adding"   
          
          
  /board/removeMedia:
    post:
      tags:
      - "Board"
      summary: "Remove Media from Board"
      description: ""
      parameters:
      - in: "body"
        name: "removeMedia"
        description: "Remove Media from Board"
        schema:
          type: object
          properties:
            boolean: 
              type: boolean
      responses:
        200:
          description: "Successfully Removed from Board"
        405:
          description: "Error while Removing Media"    
          
  /board/saveBoard:
    post:
      tags:
      - "Board"
      summary: "Save changes of the Board which are done"
      description: ""
      parameters:
      - in: "body"
        name: ""
        description: "Save changes of the Board which are done"
        schema:
          type: object
          properties:
            name: 
              type: string
      responses:
        200:
          description: "Saved Successfully"
        405:
          description: "Error Saving the Data"          
          
  /board/removeBoard:
    post:
      tags:
      - "Board"
      summary: "Remove Board"
      description: ""
      parameters:
      - in: "body"
        name: "SaveBoard"
        description: "Remove Board"
        schema:
          type: object
          properties:
            _id:
              type: string
      responses:
        200:
          description: "Board Removed Successfully"
        405:
          description: "Error Removing Board"
          
  /board/addCommentToBoard:
    post:
      tags:
      - "Board"
      summary: "Add comment to Board"
      description: ""
      parameters:
      - in: "body"
        name: "SaveComment"
        description: "Save comment to the board"
        schema:
          type: object
          properties:
            user_id:
              type: string
            comment:
              type: string
            board_id:
              type: string
      responses:
        200:
          description: "Saved Successfully"
        405:
          description: "Error Saving the Data"   
          
  /board/getBoardComment:
    post:
      tags:
      - "Board"
      summary: "Get Comments of the Board"
      description: ""
      parameters:
      - in: "body"
        name: "getBoard"
        description: "Like and unlike To Board"
        schema:
          type: object
          properties:
            user_id:
              type: string
      responses:
        200:
          description: "Return of Comment in Pagination "
        300:
          description: "No data Found"
        405:
          description: "Invalid Request"  
          
  /board/addLike:
    post:
      tags:
      - "Board"
      summary: "Like and Unlike to Board"
      description: ""
      parameters:
      - in: "body"
        name: "SaveComment"
        description: "Like and unlike To Board"
        schema:
          type: object
          properties:
            boolean:
              type: boolean
      responses:
        200:
          description: "Like true and Unlike False"
        405:
          description: "Error Saving the Data"  

  /board/shareBoard:
    post:
      tags:
      - "Board"
      summary: "Share Board"
      description: ""
      parameters:
      - in: "body"
        name: "ShareBoard"
        description: "share Board"
        schema:
          type: object
          properties:
            emails:
              type: string
            user:
              type: string  
            board:
              type: string  
      responses:
        200:
          description: "Successfully Shared"
        405:
          description: "Error Shared"  
          
# Basket API
  /basket/addTo:
    post:
      tags:
      - "Basket"
      summary: "Add to Basket"
      description: ""
      parameters:
      - in: "body"
        name: "AddBasket"
        description: "Add to Basket"
        schema:
          type: object
          properties:
            media:
              type: string
            resolution:
              type: string
      responses:
        200:
          description: "Add to basket in Boolean format"
        405:
          description: "Error in Adding Basket"      
          
          
  /basket/remove:
    post:
      tags:
      - "Basket"
      summary: "Remove From Basket"
      description: ""
      parameters:
      - in: "body"
        name: "RemoveBasket"
        description: "Remove from Basket"
        schema:
          type: object
          properties:
            media:
              type: string
            resolution:
              type: string
      responses:
        200:
          description: "Remove from basket in Boolean format"
        405:
          description: "Error in Removing Basket"  
          
  /basket/getAll:
    post:
      tags:
      - "Basket"
      summary: "Get All Basket"
      description: ""
      parameters:
      - in: "body"
        name: "GetAllBasket"
        description: "Get All Basket"
        schema:
          type: object
          properties:
            user_Id:
              type: string
      responses:
        200:
          description: "Get All basket with pagination"
        300:
          description: "No data found"
        405:
          description: "Invalid data" 
          
  /basket/confirm:
    post:
      tags:
      - "Basket"
      summary: "Confirm Basket"
      description: ""
      parameters:
      - in: "body"
        name: "ConfirmBasket"
        description: "Confirm Basket"
        schema:
          type: object
          properties:
            boolean:
              type: boolean
      responses:
        200:
          description: "Comforming the basket"
        405:
          description: "Error in Comformation" 
# Cron
  /parseDamXML:
    get:
      tags:
      - "Cron"
      summary: "Parsing of Dam XML for Data"
      description: >-
        1. Get all the new XML <br/>
        2. Parse the XML <br/>
        3. Validate the Values <br/>
        4. Save the details in Mongodb <br/>
        5. Save the Details in Solr as well


      
securityDefinitions:
  mediapool_auth:
    type: "oauth2"
    authorizationUrl: "http://mediapool.io/v2/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  User:
    type: object
    properties:
      addreses:
        type: array
        items:
          type: object
          properties: 
            name: 
              type: string
            pincode:
              type: number
            state:
              type: string
      _id:
        type: string
        format: objectId
        example: 507f1f77bcf86cd799439011
      accessToken:
        type: string
        example: 829739238729
      name:
        type: string 
        example: chintan
      profilePic:
        type: string 
        example: http://mediapool.io:4400/images/tui.png
      email:
        type: string  
        format: email  
        example: chintan.shah@sptr.co
      accessLevel:
        type: string
        example: Admin
      onesignal:
        type: string  
        example: 507f1f77bcf86cd799439011
      lastLogin:
        type: string
        format: date-time
        example: 2016-10-05T14:35:33.593Z
      boardCount:
        type: number
        example: 102
      basket:
        type: array
        description: Array of Media ObjectId's
        items:
          type: string
          format: objectId
          description: Media
          example: 507f1f77bcf86cd799439011
  Media:
    type: object
    properties:
      _id:
        type: number
        format: objectId
        example: 507f1f77bcf86cd799439011
      name:
        type: string
        example: Robinson Club Landskron (AC1813116)
      classifications: 
        type: array
        description: Array of Classifications
        example:
            - /Tags/Product/TUI Chain/ROBINSON
            - /Tags/Product/Market Concept/ROBINSON
        items:
          type: string
      fields: 
        type: array
        example:
            imageWidth: 6144.000000
            imageHeight: 4096.000000
        items:
          type: object
          properties:
            field: 
              type: string
            value:
              type: string
      url:
        type: string
        example: robinson-club-landskron
      mimeType:
        type: string
        example: "image/jpeg"
      mediaType:
        type: string
        example: "Image"
      keyword: 
        type: array
        example: 
          - Accommodations
          - General facilities
        items:
          type: string
        
      files:
        type: array
        items:
          type: object
          properties:
            field: 
              type: string
            value:
              type: string
        example:
          "url": "http://cdn.content.tuigroup.com/tuidamdevs3/2017_6/30_10/937cee9e-dfcd-4d34-81ff-a7a200a76806/lk58_4824.jpg"
          thumbnail: "http://cdn.content.tuigroup.com/tuidamdevs3/2017_6/30_10/937cee9e-dfcd-4d34-81ff-a7a200a76806/lk58_4824Thumbnail.jpg"
  Board:
    type: object
    properties:
      _id:
        type: string
        format: objectId
        example: 507f1f77bcf86cd799439011
      name:
        type: string
        example: "Beaches in Europe"
      user:
        type: string
        description: User
        format: objectId
        example: 507f1f77bcf86cd799439011
      medias:
        description: Array of Media Objects and Sequence 
        type: array
        items:
          type: object
          properties: 
            media: 
              type: string 
              description: Media
              format: objectId
            sequence: 
              type: number
        example: 
          - media: 507f1f77bcf86cd799439011
            sequence: 0
          - media: 507f1f77bcf86cd799439011
            sequence: 1
          - media: 507f1f77bcf86cd799439011
            sequence: 2
      comment:
        type: object
        properties: 
          user: 
            type: string
            description: User
            format: objectId
            example: 507f1f77bcf86cd799439011
          timestamp: 
            type: string
            format: date-time
            example: 2016-10-05T14:35:33.593Z
          comment: 
            type: string
            example: "First image of the board is nice"
      urlSlug:
        type: string
        example: "beaches-in-europe"
      
  ConfirmedBasket:
    type: object
    properties:
      _id:
        type: number
        format: objectId
        example: 507f1f77bcf86cd799439011
      user:
        type: string
        description: User
        format: objectId
        example: 507f1f77bcf86cd799439011
      media:
        type: array
        description: Array of Media Object
        example: 
          - 507f1f77bcf86cd799439011
          - 507f1f77bcf86cd799439011
          - 507f1f77bcf86cd799439011
          - 507f1f77bcf86cd799439011
        items: 
          type: object
          properties: 
            media: 
              type: string
              description: Media
      zip:
        type: string
        example: "507f1f77bcf86cd799439011.zip"
      expiryTime: 
        type: string
        format: date-time
        example: 2016-10-05T14:35:33.593Z
      zipCompletionTime: 
        type: string
        format: date-time  
        example: 2016-10-05T14:35:33.593Z
  Config:
    type: object
    properties:
      _id:
        type: string
        format: objectID
        example: "507f1f77bcf86cd799439011"
      name:
        type: string
        example: about
      value:
        type: string
        example: Find high resolution royalty-free images, editorial stock photos, vector art, video footage clips and stock music licensing at the richest image search photo library online.
  FeaturesBoard:
    type: object
    properties:
      _id: 
        type: string
        format: objectID
        example: "507f1f77bcf86cd799439011"
      board:
        type: string
        format: objectID
        example: "507f1f77bcf86cd799439011"
        description: Board
      sequence: 
        type: number
        example: 1
  SearchLogs:
    type: object
    properties:
      _id: 
        type: string
        format: objectID
        example: "507f1f77bcf86cd799439011"
      user:
        type: string
        format: objectID
        example: "507f1f77bcf86cd799439011"
        description: User
      search:
        type: string
        example: beach
      filters:
        type: string
        exmaple: 
          classifications: /Geotree/Austria (LO68010419)/Carinthia (LO36653637)/Villach
      timestamp:
        type: string
        format: date-time
        example: 2016-10-05T14:35:33.593Z
  MediaLogs:
    type: object
    properties: 
      id: 
        type: string
        format: objectID
        example: "507f1f77bcf86cd799439011"
      user:
        type: string
        description: User
        format: objectID
        example: "507f1f77bcf86cd799439011"
      media:
        type: string
        description: User
        format: objectID
        example: "507f1f77bcf86cd799439011"
      event:
        type: string
        example: "ViewDetailPage"
      timestamp:
        type: string
        format: date-time
        example: 2016-10-05T14:35:33.593Z
  Admins:
    type: object
    properties:
      name: 
        type: string
